language: elixir
dist: bionic
services:
  - docker
elixir:
  - 1.6.5
otp_release:
  - 20.3
env:
  global:
    - RABBITMQ_HOST=localhost MIX_ENV=test
  jobs:
    - RABBITMQ_VERSION=3.7.15
cache:
  directories:
    - deps
    - _build
before_install:
  - docker pull rabbitmq:$RABBITMQ_VERSION
  - docker run -d -p 127.0.0.1:5672:5672 -p 127.0.0.1:15672:15672 rabbitmq:$RABBITMQ_VERSION
before_script:
  # Needed or Elixir 1.6 will fail due to a non-updated index
  - ~/.mix/rebar3 update
script:
  - mix coveralls.travis
