stages:
    - build
    - deploy

before_script:
    - mix local.hex --force
    - mix local.rebar

variables:
    APPLICATION_NAME: astarte_housekeeping
    CASSANDRA_CLUSTER_NAME: astartetest

mix:test-ci:
    image: elixir:1.8.1
    services:
        - cassandra:3.11.4
        - rabbitmq:3.7.15
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
        - mix format --check-formatted
    cache:
        paths:
            - deps
    except:
        - branches@Astarte-NG/astarte_housekeeping

mix:build:
    image: elixir:1.8.1
    services:
        - cassandra:3.11.4
        - rabbitmq:3.7.15
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
        - export MIX_ENV=dev
        - mix release
    cache:
        paths:
            - deps
    only:
        - master@Astarte-NG/astarte_housekeeping

mix:release-build:
    image: elixir:1.8.1
    services:
        - cassandra:3.11.4
        - rabbitmq:3.7.15
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
        - export MIX_ENV=prod
        - mix release
    cache:
        paths:
            - deps
    only:
        - tags@Astarte-NG/astarte_housekeeping

docker:snapshot-container:
    image: docker:latest
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - master@Astarte-NG/astarte_housekeeping
    script:
        - docker build -t $DOCKER_REGISTRY/astarte-ng/astarte_housekeeping:snapshot .
        - docker push $DOCKER_REGISTRY/astarte-ng/astarte_housekeeping:snapshot

docker:testing-container:
    image: docker:latest
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - testing@Astarte-NG/astarte_housekeeping
    script:
        - docker build -t $DOCKER_REGISTRY/astarte-ng/astarte_housekeeping:testing .
        - docker push $DOCKER_REGISTRY/astarte-ng/astarte_housekeeping:testing
