stages:
    - build
    - deploy

before_script:
    - mix local.hex --force
    - mix local.rebar --force

variables:
    APPLICATION_NAME: astarte_trigger_engine

mix:test-ci:
    image: elixir:1.6
    stage: build
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
    script:
        - export MIX_ENV=test
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix coveralls
    cache:
        paths:
            - deps
    except:
        - branches@Astarte-NG/astarte_trigger_engine

mix:build:
    image: elixir:1.6
    stage: build
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
    script:
        - export MIX_ENV=test
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix coveralls
        - export MIX_ENV=dev
        - mix release
    cache:
        paths:
            - deps
    only:
        - master@Astarte-NG/astarte_trigger_engine

mix:release-build:
    image: elixir:1.6
    stage: build
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
    script:
        - export MIX_ENV=prod
        - mix deps.get --force
        - mix deps.compile --force
        - mix compile --force
        - mix test
        - mix release
    cache:
        paths:
            - deps
    only:
        - tags@Astarte-NG/astarte_trigger_engine

docker:snapshot-container:
    image: docker:latest
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - master@Astarte-NG/astarte_trigger_engine
    script:
        - docker build -t $DOCKER_REGISTRY/astarte-ng/astarte_trigger_engine:snapshot .
        - docker push $DOCKER_REGISTRY/astarte-ng/astarte_trigger_engine:snapshot

docker:testing-container:
    image: docker:latest
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - testing@Astarte-NG/astarte_trigger_engine
    script:
        - docker build -t $DOCKER_REGISTRY/astarte-ng/astarte_trigger_engine:testing .
        - docker push $DOCKER_REGISTRY/astarte-ng/astarte_trigger_engine:testing
