name: Build and Test Astarte Generators

on:
  # Run when pushing to stable branches
  push:
    paths:
      - "libs/astarte_generators/**"
      - ".github/workflows/astarte-libs-build-workflow.yaml"
      - ".github/workflows/astarte-generators-workflow.yaml"
      - ".github/codecov.yml"
    branches:
      - "master"
      - "release-*"

  # Run on branch/tag creation
  create:

  # Run on pull requests for astarte_generators lib
  pull_request:
    paths:
      - "libs/astarte_generators/**"
      - ".github/workflows/astarte-libs-build-workflow.yaml"
      - ".github/workflows/astarte-generators-workflow.yaml"
      - ".github/codecov.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  astarte_generators:
    uses: ./.github/workflows/astarte-libs-build-workflow.yaml
    with:
      lib: "astarte_generators"
    secrets: inherit
