name: Astarte build

on:
  workflow_call:
  workflow_dispatch:


jobs:
  astarte-build:
    name: Astarte build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        app:
          - name: astarte-housekeeping
            dockerfile: apps/astarte_housekeeping/Dockerfile
          - name: astarte-realm-management
            dockerfile: apps/astarte_realm_management/Dockerfile
          - name: astarte-pairing
            dockerfile: apps/astarte_pairing/Dockerfile
          - name: astarte-appengine-api
            dockerfile: apps/astarte_appengine_api/Dockerfile
          - name: astarte-data-updater-plant
            dockerfile: apps/astarte_data_updater_plant/Dockerfile
          - name: astarte-trigger-engine
            dockerfile: apps/astarte_trigger_engine/Dockerfile
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase Repo Name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.app.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.app.dockerfile }}
          push: false
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO_NAME }}:buildcache,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/${{ matrix.app.name }}.tar

      - name: Upload ${{ matrix.app.name }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: astarte-images
          path: ${{ runner.temp }}/${{ matrix.app.name }}.tar
